"""Markdown reporter."""

from pipelineiq.models import AnalysisResult, Severity


class MarkdownReporter:
    """Markdown output reporter."""
    
    SEVERITY_EMOJI = {
        Severity.CRITICAL: "🔴",
        Severity.HIGH: "🟠",
        Severity.MEDIUM: "🟡",
        Severity.LOW: "🔵",
        Severity.INFO: "ℹ️",
    }
    
    def render(self, result: AnalysisResult) -> str:
        """Render analysis result to Markdown string."""
        lines = []
        
        # Header
        lines.append(f"# PipelineIQ Analysis Report")
        lines.append("")
        lines.append(f"**Pipeline:** {result.pipeline.name}")
        lines.append(f"**Platform:** {result.pipeline.platform.value}")
        lines.append(f"**File:** `{result.pipeline.file_path}`")
        lines.append("")
        
        # Summary
        lines.append("## Summary")
        lines.append("")
        score = result.summary.score
        score_badge = "🟢" if score >= 80 else "🟡" if score >= 50 else "🔴"
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Score | {score_badge} **{score}/100** |")
        lines.append(f"| Total Findings | {result.summary.total_findings} |")
        
        if result.summary.estimated_time_savings:
            lines.append(f"| Est. Time Savings | {result.summary.estimated_time_savings} |")
        
        lines.append("")
        
        # Severity breakdown
        if result.summary.by_severity:
            lines.append("### By Severity")
            lines.append("")
            for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO]:
                count = result.summary.by_severity.get(sev, 0)
                if count > 0:
                    emoji = self.SEVERITY_EMOJI[sev]
                    lines.append(f"- {emoji} **{sev.value}**: {count}")
            lines.append("")
        
        # Findings
        if result.findings:
            lines.append("## Findings")
            lines.append("")
            
            for i, finding in enumerate(result.findings, 1):
                emoji = self.SEVERITY_EMOJI[finding.severity]
                lines.append(f"### {i}. {emoji} {finding.rule_name}")
                lines.append("")
                lines.append(f"**Severity:** {finding.severity.value}")
                lines.append(f"**Category:** {finding.category.value}")
                lines.append(f"**Location:** `{finding.location.stage or finding.location.file}`")
                lines.append("")
                lines.append(f"> {finding.message}")
                lines.append("")
                lines.append(f"**Suggestion:** {finding.suggestion}")
                if finding.estimated_impact:
                    lines.append(f"**Impact:** {finding.estimated_impact}")
                lines.append("")
        
        # AI Suggestions
        if result.ai_suggestions:
            lines.append("## AI Suggestions")
            lines.append("")
            for suggestion in result.ai_suggestions:
                lines.append(f"- {suggestion}")
            lines.append("")
        
        # Critical Path
        if result.summary.critical_path:
            lines.append("## Critical Path")
            lines.append("")
            path = " → ".join(f"`{s}`" for s in result.summary.critical_path)
            lines.append(path)
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append(f"*Generated by PipelineIQ v{result.analyzer_version} in {result.execution_time_ms}ms*")
        
        return "\n".join(lines)
